apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/llm-d/llm-d/guides/optimized-baseline/modelserver/gpu/vllm/gke?ref=main
patches:
  - path: patch-gke-timeslice.yaml
