apiVersion: apps/v1
kind: Deployment
metadata:
  name: optimized-baseline-nvidia-gpu-vllm-decode
spec:
  replicas: 1
  template:
    spec:
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      containers:
        - name: modelserver
          args:
            - "Qwen/Qwen3-0.6B"
            - "--disable-access-log-for-endpoints=/health,/metrics,/v1/models"
            - "--tensor-parallel-size=1"
            - "--gpu-memory-utilization=0.10"
            - "--max-model-len=2048"
            - "--enforce-eager"
            - "--max-num-seqs=4"
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: token
                  optional: true
          resources:
            limits:
              cpu: "2"
              memory: "6Gi"
              nvidia.com/gpu: "1"
            requests:
              cpu: "200m"
              memory: "2Gi"
              nvidia.com/gpu: "1"
